# Generated by Django 3.0.7 on 2023-05-09 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_management_app', '0002_auto_20230509_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clerk',
            old_name='admin',
            new_name='user',
        ),
    ]
