# Generated by Django 3.0.7 on 2023-05-09 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_management_app', '0003_auto_20230509_0644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliers',
            old_name='admin',
            new_name='user',
        ),
    ]
