
from django.urls import path
from . import views
from . import ManagerViews, ClerkViews, SupplierViews


urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.loginPage, name="login"),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('doLogin/', views.doLogin, name="doLogin"),
    path('get_user_details/', views.get_user_details, name="get_user_details"),
    path('logout_user/', views.logout_user, name="logout_user"),
    path('admin_dashboard/', ManagerViews.admin_dashboard, name="admin_dashboard"),
    path('admin_home/', ManagerViews.admin_home, name="admin_home"),
    path('add_clerk/', ManagerViews.add_clerk, name="add_clerk"),
    path('add_clerk_save/', ManagerViews.add_clerk_save, name="add_clerk_save"),
    path('manage_clerk/', ManagerViews.manage_clerk, name="manage_clerk"),
    path('edit_clerk/<clerk_id>/', ManagerViews.edit_clerk, name="edit_clerk"),
    path('edit_clerk_save/', ManagerViews.edit_clerk_save, name="edit_clerk_save"),
    path('delete_clerk/<clerk_id>/', ManagerViews.delete_clerk, name="delete_clerk"),
    path('add_coffee_types/', ManagerViews.add_coffee_types, name="add_coffee_types"),
    path('add_coffee_types_save/', ManagerViews.add_coffee_types_save, name="add_coffee_types_save"),
    path('manage_coffee_types/', ManagerViews.manage_coffee_types, name="manage_coffee_types"),
    path('edit_coffee_types/<coffee_types_id>/', ManagerViews.edit_coffee_types, name="edit_coffee_types"),
    path('edit_coffee_types_save/', ManagerViews.edit_coffee_types_save, name="edit_coffee_types_save"),
    path('delete_coffee_types/<coffee_types_id>/', ManagerViews.delete_coffee_types, name="delete_coffee_types"),
    path('manage_season/', ManagerViews.manage_season, name="manage_season"),
    path('add_season/', ManagerViews.add_season, name="add_season"),
    path('add_season_save/', ManagerViews.add_season_save, name="add_season_save"),
    path('edit_season/<season_id>', ManagerViews.edit_season, name="edit_season"),
    path('edit_season_save/', ManagerViews.edit_season_save, name="edit_season_save"),
    path('delete_season/<season_id>/', ManagerViews.delete_season, name="delete_season"),
    path('add_suppliers/', ManagerViews.add_suppliers, name="add_suppliers"),
    path('add_suppliers_save/', ManagerViews.add_suppliers_save, name="add_suppliers_save"),
    path('edit_suppliers/<suppliers_id>', ManagerViews.edit_suppliers, name="edit_suppliers"),
    path('edit_suppliers_save/', ManagerViews.edit_suppliers_save, name="edit_suppliers_save"),
    path('manage_suppliers/', ManagerViews.manage_suppliers, name="manage_suppliers"),
    path('delete_suppliers/<suppliers_id>/', ManagerViews.delete_suppliers, name="delete_suppliers"),
    path('add_batch/', ManagerViews.add_batch, name="add_batch"),
    path('add_batch_save/', ManagerViews.add_batch_save, name="add_batch_save"),
    path('manage_batch/', ManagerViews.manage_batch, name="manage_batch"),
    path('edit_batch/<batch_id>/', ManagerViews.edit_batch, name="edit_batch"),
    path('edit_batch_save/', ManagerViews.edit_batch_save, name="edit_batch_save"),
    path('delete_batch/<batch_id>/', ManagerViews.delete_batch, name="delete_batch"),
    path('check_email_exist/', ManagerViews.check_email_exist, name="check_email_exist"),
    path('check_username_exist/', ManagerViews.check_username_exist, name="check_username_exist"),
    path('suppliers_feedback_message/', ManagerViews.suppliers_feedback_message, name="suppliers_feedback_message"),
    path('suppliers_feedback_message_reply/', ManagerViews.suppliers_feedback_message_reply, name="suppliers_feedback_message_reply"),
    path('clerk_feedback_message/', ManagerViews.clerk_feedback_message, name="clerk_feedback_message"),
    path('clerk_feedback_message_reply/', ManagerViews.clerk_feedback_message_reply, name="clerk_feedback_message_reply"),
    path('supplier_leave_view/', ManagerViews.supplier_leave_view, name="supplier_leave_view"),
    path('supplier_leave_approve/<leave_id>/', ManagerViews.supplier_leave_approve, name="supplier_leave_approve"),
    path('supplier_leave_reject/<leave_id>/', ManagerViews.supplier_leave_reject, name="supplier_leave_reject"),
    path('clerk_leave_view/', ManagerViews.clerk_leave_view, name="clerk_leave_view"),
    path('clerk_leave_approve/<leave_id>/', ManagerViews.clerk_leave_approve, name="clerk_leave_approve"),
    path('clerk_leave_reject/<leave_id>/', ManagerViews.clerk_leave_reject, name="clerk_leave_reject"),
    path('admin_view_attendance/', ManagerViews.admin_view_attendance, name="admin_view_attendance"),
    path('admin_get_attendance_dates/', ManagerViews.admin_get_attendance_dates, name="admin_get_attendance_dates"),
    path('admin_get_attendance_supplier/', ManagerViews.admin_get_attendance_supplier, name="admin_get_attendance_supplier"),
    path('admin_profile/', ManagerViews.admin_profile, name="admin_profile"),
    path('admin_profile_update/', ManagerViews.admin_profile_update, name="admin_profile_update"),
    


    # URLS for Clerk
    path('clerk_home/', ClerkViews.clerk_home, name="clerk_home"),
    path('clerk_take_attendance/', ClerkViews.clerk_take_attendance, name="clerk_take_attendance"),
    path('get_suppliers/', ClerkViews.get_suppliers, name="get_suppliers"),
    path('save_attendance_data/', ClerkViews.save_attendance_data, name="save_attendance_data"),
    path('clerk_update_attendance/', ClerkViews.clerk_update_attendance, name="clerk_update_attendance"),
    path('get_attendance_dates/', ClerkViews.get_attendance_dates, name="get_attendance_dates"),
    path('get_attendance_supplier/', ClerkViews.get_attendance_supplier, name="get_attendance_supplier"),
    path('update_attendance_data/', ClerkViews.update_attendance_data, name="update_attendance_data"),
    path('clerk_apply_leave/', ClerkViews.clerk_apply_leave, name="clerk_apply_leave"), 
    path('clerk_apply_leave_save/', ClerkViews.clerk_apply_leave_save, name="clerk_apply_leave_save"),
    path('clerk_feedback/', ClerkViews.clerk_feedback, name="clerk_feedback"),
    path('clerk_feedback_save/', ClerkViews.clerk_feedback_save, name="clerk_feedback_save"),
    path('clerk_profile/', ClerkViews.clerk_profile, name="clerk_profile"),
    path('clerk_profile_update/', ClerkViews.clerk_profile_update, name="clerk_profile_update"),
    path('clerk_add_coffee_data/', ClerkViews.clerk_add_coffee_data, name="clerk_add_coffee_data"),
    path('clerk_add_coffee_data_save/', ClerkViews.clerk_add_coffee_data_save, name="clerk_add_coffee_data_save"),

    # URSL for Supplier
    path('supplier_home/', SupplierViews.supplier_home, name="supplier_home"),
    path('supplier_view_attendance/', SupplierViews.supplier_view_attendance, name="supplier_view_attendance"),
    path('supplier_view_attendance_post/', SupplierViews.supplier_view_attendance_post, name="supplier_view_attendance_post"),
    path('supplier_apply_leave/', SupplierViews.supplier_apply_leave, name="supplier_apply_leave"),
    path('supplier_apply_leave_save/', SupplierViews.supplier_apply_leave_save, name="supplier_apply_leave_save"),
    path('supplier_feedback/', SupplierViews.supplier_feedback, name="supplier_feedback"),
    path('supplier_feedback_save/', SupplierViews.supplier_feedback_save, name="supplier_feedback_save"),
    path('supplier_profile/', SupplierViews.supplier_profile, name="supplier_profile"),
    path('supplier_profile_update/', SupplierViews.supplier_profile_update, name="supplier_profile_update"),
    path('supplier_view_result/', SupplierViews.supplier_view_result, name="supplier_view_result"),

]
